### ISSUE TITLE
VM annotation

### ISSUE THREAD

**Issue by mfalesni** [psphere-project/psphere#22]
I haven't found how to update VM's annotation from within psphere (`vm.summary.config.annotation`). I would like to set some metadata in there.

Is it a missing feature or I was blind and haven't found that?

**Comment by michaelrice** [comment]
Personally Id use extraConfig for that since it is a key value thing to begin with and the annotation is just text. Im not sure how to do these things using psphere but here is an [example](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_vm_extra_config_tags.py) using pyVmomi. I have held all kinds of stuff including pretty large base64 encoded files as values. The note way is a bad idea IMO becuase anyone could change it from the web client or fat client. The only advantage it has is that it can be seen from those as well where the extraConfig can not. Here is a sample using pyVmomi for setting the [annotation](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/set_note.py). Im sure psphere has a way to drop to the actual objects like pyVmomi is doing so I hope that helps you get it done.
